// tests/integration/webmcp.spec.ts
import { expect, test } from '@playwright/test';

test.beforeAll(async () => {
  const { existsSync } = await import('node:fs');
  if (!existsSync('examples/fixture-sb/storybook-static/manifests/components.json')) {
    throw new Error('Run `npm --prefix examples/fixture-sb run build-storybook` before the e2e tests.');
  }
});

test('three storybook.* tools are registered and callable', async ({ page }) => {
  const consoleErrors: string[] = [];
  page.on('console', (m) => {
    if (m.type() === 'error') {
      const text = m.text();
      // Ignore the expected 404 for the optional docs.json manifest — the
      // loadManifests helper handles it gracefully (a.ok check), but the
      // browser still logs the failed network request to the console.
      if (text.includes('404') || text.toLowerCase().includes('failed to load resource')) return;
      consoleErrors.push(text);
    }
  });

  await page.goto('/');
  // Wait for networkidle first so the manager bundles finish loading, then
  // wait for navigator.modelContext to be present with listTools.
  await page.waitForLoadState('networkidle');
  await page.waitForFunction(
    () => 'modelContext' in navigator && typeof (navigator as any).modelContext?.listTools === 'function',
    null,
    { timeout: 30_000 },
  );

  // listTools() is synchronous on the @mcp-b/global polyfill.
  const names = await page.evaluate(() => {
    const tools = (navigator as any).modelContext.listTools() as Array<{ name: string }>;
    return tools.map((t) => t.name).sort();
  });
  expect(names).toEqual([
    'storybook.get-documentation',
    'storybook.get-documentation-for-story',
    'storybook.list-all-documentation',
  ]);

  // callTool takes { name, arguments } — NOT (name, args) as two positional params.
  const listResult = await page.evaluate(async () => {
    const r = await (navigator as any).modelContext.callTool({
      name: 'storybook.list-all-documentation',
      arguments: {},
    });
    return JSON.parse(r.content[0].text);
  });

  // Three components were authored in the fixture. Exact ids are generated by
  // Storybook from the story title and may include path prefixes — assert the
  // count and the presence of each component name (case-insensitive substring).
  expect(listResult.components).toHaveLength(3);
  const idsLower = listResult.components
    .map((c: { id: string }) => c.id.toLowerCase())
    .join(' ');
  for (const name of ['button', 'card', 'input']) expect(idsLower).toContain(name);

  expect(consoleErrors, consoleErrors.join('\n')).toEqual([]);
});
