/**
 * Storybook 10 manifest types.
 *
 * Source of truth: src/tools/__fixtures__/components.realistic.json
 * (a verbatim copy of the storybook-static/manifests/components.json emitted by
 * `examples/fixture-sb` at build time).
 *
 * Adjust this file when Storybook's manifest schema changes.
 *
 * Key deviations from the spec skeleton:
 * - Version field is `v: number` (NOT `schemaVersion`) — matches ComponentsManifest
 *   in storybook/dist/types/index.d.ts.
 * - No top-level `props` on ComponentEntry; props live inside `reactDocgen`.
 * - Stories have `id`, `name`, `snippet` (not `args`/`parameters`).
 * - `jsDocTags` is always present as Record<string, string[]>.
 * - `import` field (component import string) is present.
 * - No `docs` or `tags` fields on component entries in the real output.
 * - `docs.json` was NOT produced by the build (only components.json).
 *   DocsManifest is typed speculatively based on addon-docs source (v: 0, docs: {...}).
 */

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

/** Schema version emitted by Storybook. The real field name is `v` (not schemaVersion). */
export type SchemaVersion = number;

// ---------------------------------------------------------------------------
// Components manifest
// ---------------------------------------------------------------------------

/**
 * A single story entry within a component.
 * Source: components.realistic.json > components[id].stories[n]
 */
export type StoryEntry = {
  id: string;
  name: string;
  /** JSX snippet generated by experimental_enrichCsf / code-examples feature */
  snippet?: string;
  description?: string;
  summary?: string;
  error?: {
    name: string;
    message: string;
  };
};

/**
 * A react-docgen prop type descriptor.
 * Source: components.realistic.json > components[id].reactDocgen.props[name].tsType
 */
export type PropType = {
  name: string;
  raw?: string;
  elements?: PropType[];
};

/**
 * A single prop definition as emitted by react-docgen.
 * Source: components.realistic.json > components[id].reactDocgen.props[name]
 */
export type PropDef = {
  required: boolean;
  tsType: PropType;
  description: string;
  defaultValue?: {
    value: string;
    computed: boolean;
  };
};

/**
 * The react-docgen block for a component.
 * Source: components.realistic.json > components[id].reactDocgen
 * This field is present when docgen is `react-docgen` (the default).
 * With `react-docgen-typescript` or `react-component-meta` the shape may differ.
 */
export type ReactDocgenData = {
  description: string;
  methods: unknown[];
  displayName: string;
  definedInFile: string;
  actualName: string;
  exportName: string;
  props: Record<string, PropDef>;
};

/**
 * A single prop definition as emitted by react-docgen-typescript.
 * Field shape differs from the vanilla react-docgen PropDef:
 *   - `type: { name }` instead of `tsType: { name, raw? }`
 *   - `defaultValue: { value } | null` instead of optional/missing
 *   - prop record entries also carry their own `name` field
 *
 * Source: storybook 10 with `typescript.reactDocgen: 'react-docgen-typescript'`
 * (e.g. scality/core-ui).
 */
export type ReactDocgenTypescriptPropDef = {
  name: string;
  required: boolean;
  type: { name: string };
  description: string;
  defaultValue: { value: string } | null;
};

export type ReactDocgenTypescriptData = {
  description: string;
  displayName: string;
  exportName: string;
  filePath: string;
  methods: unknown[];
  props: Record<string, ReactDocgenTypescriptPropDef>;
  tags?: Record<string, unknown>;
};

/**
 * A single component entry in the components manifest.
 * Source: components.realistic.json > components[id]
 */
export type ComponentEntry = {
  id: string;
  /** Last segment of the stories title, e.g. "Button" */
  name: string;
  /** Relative path to the stories file, e.g. "./src/Button.stories.tsx" */
  path: string;
  stories: StoryEntry[];
  /** Component import string, e.g. `import { Button } from "fixture-sb";` */
  import?: string;
  /** JSDoc tag map extracted from component JSDoc, e.g. { param: ["label"] } */
  jsDocTags: Record<string, string[]>;
  description?: string;
  summary?: string;
  /** Present when docgenEngine is react-docgen (the default) */
  reactDocgen?: ReactDocgenData;
  /** Present when docgenEngine is react-docgen-typescript */
  reactDocgenTypescript?: ReactDocgenTypescriptData;
  /** Present when features.experimentalReactComponentMeta is true */
  reactComponentMeta?: unknown;
  subcomponents?: Record<string, ComponentSubcomponentEntry>;
  error?: {
    name: string;
    message: string;
  };
};

/**
 * Subcomponent entry (subset of ComponentEntry fields).
 * Source: storybook/dist/types/index.d.ts > ComponentSubcomponentManifest
 */
export type ComponentSubcomponentEntry = {
  name: string;
  path: string;
  description?: string;
  import?: string;
  summary?: string;
  jsDocTags: Record<string, string[]>;
  error?: {
    name: string;
    message: string;
  };
};

/**
 * The top-level components manifest object.
 * Source: components.realistic.json (top-level shape)
 *
 * NOTE: The version field is `v`, not `schemaVersion`.
 * In SUPPORTED_VERSIONS checks, compare against `manifest.v`.
 */
export type ComponentsManifest = {
  /** Schema version. Currently 0 in Storybook 10.4. */
  v: SchemaVersion;
  components: Record<string, ComponentEntry>;
  meta?: {
    /** Docgen engine used: 'react-docgen' | 'react-docgen-typescript' | 'react-component-meta' */
    docgen: string;
    durationMs: number;
  };
};

// ---------------------------------------------------------------------------
// Docs manifest (speculative — not emitted by the fixture build)
// ---------------------------------------------------------------------------

/**
 * A single unattached MDX doc entry.
 * Source: @storybook/addon-docs/dist/preset.js (speculative — docs.json was not
 * produced by the fixture-sb build because there are no unattached MDX files).
 */
export type DocsManifestEntry = {
  id: string;
  title?: string;
  content?: string;
  tags?: string[];
};

/**
 * The top-level docs manifest object.
 * Source: @storybook/addon-docs preset source — `{ v: 0, docs: {...} }`.
 * NOTE: The inner key is `docs`, not `entries`.
 */
export type DocsManifest = {
  /** Schema version. Currently 0 in Storybook 10.4. */
  v: SchemaVersion;
  docs: Record<string, DocsManifestEntry>;
};
